config/routes.rb
Modo::Application.routes.draw do
  resources :jobs

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :comment, :tag, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.js { flash.now[:notice] = 'Thank you for submitting your comment'}
      else
        format.js { flash[:error] = @job.errors.full_messages.join("<br/>") }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_comment_box.html.erb
<div id="model_box" class="modal hide fade"
  tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"
      aria-hidden="true">×</button>
    <h3 id="myModalLabel">
      Add comment
    </h3>
  </div>
  
  <div class="modal-body">
    <%= form_for(@job, :url => jobs_path,
    :remote => true, :html => { :method => :post, :class=>"form-horizontal" } ) do |f| %>
      <span class="error"></span>
      <div class="control-group">
        <label class="control-label" for="inputEmail">Comment</label>
        <div class="controls">
          <%= f.text_area :comment, :class => "span2", :rows => '4', :style=>"width: 223px; height: 84px;" %>
          <p id="counter"></p>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">Tag</label>
        <div class="controls">
          <%= f.text_field :tag, :style=>"width: 223px;" %>
        </div>
      </div>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true"><p class="ok_btn">Close</p></button>
    <%= f.submit "Submit", :class=>"btn btn-primary submit", 'aria-hidden'=>"true" %>
  </div>
  <% end %>  
</div>

app/views/jobs/create.js.erb
$(".flash_message").html("<%= escape_javascript(render :partial => 'shared/flash_messages') %>");
$('#model_box').modal('hide');
$('#job_comment').val('');
$('#job_tag').val('');
$('<p id="counter">You have 150 characters remaining</p>').replaceAll('#counter');

app/views/jobs/index.html.erb
<h1>Listing jobs</h1>

<table>
  <tr>
    <th>Comment</th>
    <th>Tag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.comment %></td>
    <td><%= job.tag %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<br/><br/>
<a href="#model_box" role="button" data-toggle="modal">
  <i class="icon icon-question-sign"></i>Click here to open comment box
</a>
<%= render :partial => 'comment_box' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Modo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="flash_message">
</div>
<%= yield %>

</body>
</html>

app/views/shared/_flash_messages.html.erb
<script type="text/javascript">
  $(".alert_msg_nav_bar").removeClass("hide"); 
</script>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert_margin alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
    </div>
  <% end %>
  <% flash.discard(name) %>
<% end %>